"""Pilot structure analysis (Step 3). Reads $LEXHACK_DATA/parsed/ + raw WARC; writes analysis.md there.
    uv run python -m crawler.analyze
"""
import json
import re
from collections import Counter, defaultdict

from bs4 import BeautifulSoup

from . import config
from .frontier import Frontier
from .storage import read_record

ACTS = {"/akn/ke/act/1998/2": ("KICA (Cap. 411A)", ["29"]),
        "/akn/ke/act/1930/10": ("Penal Code (Cap. 63)", ["194", "204"]),
        "/akn/ke/act/2007/11": ("Employment Act, 2007", [])}
NAMED = {"Andare": "Geoffrey Andare v AG [2016]", "Okuta": "Jacqueline Okuta v AG [2017]",
         "Muruatetu": "Francis Karioko Muruatetu v Republic [2017]"}
COURTISH = re.compile(r"(?i)\b(court|petition|unconstitutional|declared|invalid|judgment|eKLR)\b")
FIELDS = {"citation": ["Citation", "Media Neutral Citation"], "court": ["Court"], "case number": ["Case number"],
          "date": ["Judgment date", "Date"], "judges": ["Judges"], "parties": ["Parties"],
          "legislation cited": ["Legislation cited"], "cases cited": ["Cases cited", "Case law cited"]}


def load(kind):
    d = config.parsed_dir() / kind
    return [json.loads(p.read_text()) for p in sorted(d.glob("*.json"))] if d.exists() else []


def raw_html(frontier, raw, uri):
    r = frontier.latest_response(uri)
    return read_record(raw, r["warc_file"], r["offset"])[1].decode("utf-8", "replace") if r else ""


def era(y):
    return "pre-2005" if y < 2005 else "2005-2009" if y < 2010 else "2010-2015" if y <= 2015 else \
        "2016-2021" if y < 2022 else "2022+"


def main():
    raw = config.raw_dir()
    fr = Frontier(raw / "frontier.db")
    acts, judgments, sources = load("act"), load("judgment"), {d["url"]: d for d in load("source")}
    out = ["# Pilot analysis (generated by crawler/analyze.py)\n"]
    w = out.append

    # ---- statutes ---------------------------------------------------------
    w("## Statutes\n")
    by_work = defaultdict(list)
    for a in acts:
        by_work[a["work"]].append(a)
    for work, (name, secs) in ACTS.items():
        docs = sorted(by_work.get(work, []), key=lambda d: d["expression_date"] or "")
        listed = sorted({v for d in docs for v in d["versions"]})
        got = [d["expression_date"] for d in docs]
        w(f"### {name} `{work}`\n")
        w(f"- versions listed on its pages: {', '.join(listed) or 'none (no pages captured)'}")
        w(f"- versions fetched (from the Wayback Machine): {', '.join(got) or 'none'}\n")
        for d in docs:
            w(f"- `{d['expression_date']}`: display={d['display_type']}, sections={len(d['sections'])}, "
              f"remarks={len(d['remarks'])}")
        for sec in secs:
            w(f"\n#### s.{sec}\n")
            for d in docs:
                hit = [s for s in d["sections"] if re.search(rf"(^|__)sec_{sec}$", s["eid"])]
                if not hit:
                    w(f"- `{d['expression_date']}`: no section with eId ending `sec_{sec}`")
                    continue
                eid = hit[0]["eid"]
                html = raw_html(fr, raw, d["retrieved_from"])
                el = BeautifulSoup(html, "lxml").find(attrs={"data-eid": eid})
                rem = [r for r in d["remarks"] if r["eid"] and (r["eid"] == eid or r["eid"].startswith(eid + "__"))]
                w(f"- `{d['expression_date']}`: eId **`{eid}`**; remarks inside: {len(rem)}")
                for r in rem:
                    w(f"  - remark (`{r['eid']}`): \"{r['text']}\"")
                if el is not None and d is docs[-1]:
                    w(f"\n  Latest version, verbatim HTML (first 900 chars):\n\n```html\n{str(el)[:900]}\n```")
        w("")
    all_rem = [(a["url"], r) for a in acts for r in a["remarks"]]
    court = [(u, r) for u, r in all_rem if COURTISH.search(r["text"])]
    w(f"### Remarks across all fetched statute pages\n\n- `akn-remark` spans: **{len(all_rem)}** over {len(acts)} pages")
    w(f"- mentioning court / petition / unconstitutional / declared / invalid / judgment / eKLR: **{len(court)}**\n")
    for u, r in court[:10]:
        w(f"  - {u} `{r['eid']}`: \"{r['text'][:400]}\"")
    enr = sum("content-and-enrichments" in raw_html(fr, raw, a["retrieved_from"]) for a in acts[:1])
    w(f"\n- Enrichment gutter (`content-and-enrichments`) present in page markup: {bool(enr)}; its content is "
      "loaded client-side, so annotations delivered that way are NOT in archived static HTML.\n")

    # ---- judgments --------------------------------------------------------
    w("## Judgments\n")
    named = {k: [j for j in judgments if k.lower() in (j["title"] or "").lower()] for k in NAMED}
    w(f"Judgments parsed: {len(judgments)}\n")
    w("### Metadata fields (`<dl class=\"document-metadata-list\">`): null/empty rate\n")
    labels = Counter(k for j in judgments for k in j["metadata"])
    w("All labels seen: " + ", ".join(f"{k} ({n})" for k, n in labels.most_common()) + "\n")
    w("| field | present & non-empty | null/empty rate |\n|---|---|---|")
    for f, keys in FIELDS.items():
        n = sum(any((j["metadata"].get(k) or "").strip() for k in keys) for j in judgments)
        w(f"| {f} | {n}/{len(judgments)} | {1 - n / max(1, len(judgments)):.0%} |")
    w("\n### Full HTML text vs PDF-only, by era (year of the URI)\n")
    tab = defaultdict(Counter)
    for j in judgments:
        y = int(re.search(r"/judgment/[a-z]+/(\d{4})/", j["url"]).group(1))
        tab[era(y)]["html" if j["display_type"] != "pdf" and len(j["text"]) > 500 else "pdf-only"] += 1
    w("| era | html | pdf-only | html share |\n|---|---|---|---|")
    for e in ["pre-2005", "2005-2009", "2010-2015", "2016-2021", "2022+"]:
        c = tab.get(e)
        if c:
            w(f"| {e} | {c['html']} | {c['pdf-only']} | {c['html'] / (c['html'] + c['pdf-only']):.0%} |")
    tot = sum(c["html"] for c in tab.values())
    w(f"\nOverall: {tot}/{len(judgments)} with full HTML text.\n")

    w("### Links to legislation\n")
    act_links = [[l for l in j["akn_links"] if "/akn/ke/act/" in l] for j in judgments]
    with_any = sum(bool(x) for x in act_links)
    with_prov = sum(any("#" in l or "~" in l for l in x) for x in act_links)
    w(f"- judgments with ≥1 `/akn/ke/act/…` link: {with_any}/{len(judgments)}")
    w(f"- judgments with ≥1 provision-level link (`#…` or `~…`): {with_prov}/{len(judgments)}")
    ex = [l for x in act_links for l in x][:8]
    w("- examples: " + ", ".join(f"`{l}`" for l in ex) + "\n")

    w("### Named judgments\n")
    for k, label in NAMED.items():
        hits = named[k]
        if not hits:
            w(f"- **{label}**: not among fetched pages\n")
            continue
        j = hits[0]
        src = sources.get(j["source_url"] or "")
        w(f"- **{label}** → {j['title']}\n  - url: {j['url']}\n  - display: {j['display_type']}, "
          f"HTML text chars: {len(j['text'])}, source PDF fetched: {bool(src)}")
    (config.parsed_dir() / "analysis.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
